batch_size: 400
epochs: 4
wandb_project_name: BIOSCAN-CLIP-5M
using_train_seen_for_pre_train: true
dataset: bioscan_5m

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert

bioscan_bert_checkpoint: ${project_root_path}/ckpt/BarcodeBERT/5_mer/model_41.pth
model_output_dir: ${project_root_path}/ckpt/bioscan_clip
model_output_name: lora_vit_lora_barcode_bert_ssl_batch_size_400_5m
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/lora_vit_lora_barcode_bert_ssl_batch_size_400_5m/best.pth
output_dim: 768
num_workers: 8
port: 12318