batch_size: 150
epochs: 15
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-ablation_with_open_clip
using_train_seen_for_pre_train: true
dataset: bioscan_1m
disable_lora: true 

image:
  input_type: image
  model: lora_clip_image
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_clip_text

model_output_name: trained_with_bioscan_1m_image_dna_text_with_pretrained_clip
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/trained_with_bioscan_1m/image_dna_text.pth
output_dim: 768
port: 12345

for_open_clip: true
lr_scheduler: cosine
lr_config:
  min_lr: 0.000000001
  max_lr: 0.001

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: true
amp: true
