batch_size: 350
epochs: 5
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-FULL-FINE-TUNING
using_train_seen_for_pre_train: true
dataset: bioscan_5m
disable_lora: true

image:
  input_type: image
  model: lora_vit
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert

model_output_name: trained_with_bioscan_5m_image_dna_text
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/trained_with_bioscan_5m/image_dna_text.pth
output_dim: 768
port: 29501
